Controllers/ArtsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SugartwebApp.Data;
using SugartwebApp.Models;

namespace SugartwebApp.Controllers
{
    public class ArtsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ArtsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //Vista de Listado publico 
        public async Task<IActionResult> BuscarObra()
        {
            return View();
        }

        public async Task<IActionResult> IndexPublic2()
        {
            return View(await _context.arts.ToListAsync());
        }
        //buscador
        public async Task<IActionResult> ResultadoDeBusqueda(String PalabraBuscada) //Se pasa como parametro la palabra buscada
        {
            //String ResultadoDeBusqueda
            //  return "Buscaste la palabra "+ PalabraBuscada; (Se pasa al metodo a string para comprobar el funcionamiento)
            return View("IndexPublic", await _context.arts.Where(b => b.artTitle.Contains(PalabraBuscada)).ToListAsync());
            //Funcion flecha que retorna el index filtrado por la palabra que se ingreso 
        }

        [Authorize]
        // GET: Arts
        public async Task<IActionResult> Index()
        {
            return View(await _context.arts.ToListAsync());
        }


        [Authorize]
        // GET: Arts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var art = await _context.arts
                .FirstOrDefaultAsync(m => m.artId == id);
            if (art == null)
            {
                return NotFound();
            }

            return View(art);
        }

        [Authorize]
        // GET: Arts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Arts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("artId,artTitle,artValue")] Art art)
        {
            if (ModelState.IsValid)
            {
                _context.Add(art);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(art);
        }

        [Authorize]
        // GET: Arts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var art = await _context.arts.FindAsync(id);
            if (art == null)
            {
                return NotFound();
            }
            return View(art);
        }

        // POST: Arts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("artId,artTitle,artValue")] Art art)
        {
            if (id != art.artId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(art);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtExists(art.artId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(art);
        }

        [Authorize]
        // GET: Arts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var art = await _context.arts
                .FirstOrDefaultAsync(m => m.artId == id);
            if (art == null)
            {
                return NotFound();
            }

            return View(art);
        }

        [Authorize]
        // POST: Arts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var art = await _context.arts.FindAsync(id);
            _context.arts.Remove(art);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtExists(int id)
        {
            return _context.arts.Any(e => e.artId == id);
        }
    }
}

Controllers/EmailcsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SugartwebApp.Data;
using SugartwebApp.Models;

using System.Net.Mail;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;

namespace SugartwebApp.Controllers
{
    public class EmailcsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmailcsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        // GET: Emailcs
        public async Task<IActionResult> Index()
        {
            return View(await _context.emails.ToListAsync());
        }

        [Authorize]
        // GET: Emailcs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailcs = await _context.emails
                .FirstOrDefaultAsync(m => m.emailId == id);
            if (emailcs == null)
            {
                return NotFound();
            }

            return View(emailcs);
        }

        // GET: Emailcs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Emailcs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("emailId,emailFrom,emailSubject,emailBody,emailTo")] Emailcs emailcs)
        {
            //Metodo para envio de mails
            MailMessage correo = new MailMessage();

            correo.From = new MailAddress(emailcs.emailFrom, "Contacto Sugart®", System.Text.Encoding.UTF8);//email de origen
            correo.To.Add("cristian.andres.dev.send.mail@gmail.com");//email que recibe
            correo.Subject = emailcs.emailSubject; //Asunto 
            correo.Body = emailcs.emailBody;//cuerpo del correo
            correo.IsBodyHtml = true;
            correo.Priority = MailPriority.Normal;

            SmtpClient smtp = new SmtpClient();
            smtp.UseDefaultCredentials = false;
            smtp.Host = "smtp.gmail.com";//servicio smtp de gmail
            smtp.Port = 587;//puerto
            smtp.Credentials = new System.Net.NetworkCredential("cristian.andres.dev.send.mail@gmail.com", "Clave-10");//credenciales gmail usuario
            ServicePointManager.ServerCertificateValidationCallback = delegate (object s, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) { return true; };
            smtp.EnableSsl = true;

            smtp.Send(correo);
            smtp.Dispose();


            if (ModelState.IsValid)
            {
                _context.Add(emailcs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(HomeController.Index));
            }
            return RedirectToAction(nameof(HomeController.Index));
            
        }

        [Authorize]
        // GET: Emailcs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailcs = await _context.emails.FindAsync(id);
            if (emailcs == null)
            {
                return NotFound();
            }
            return View(emailcs);
        }

        [Authorize]
        // POST: Emailcs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("emailId,emailFrom,emailSubject,emailBody,emailTo")] Emailcs emailcs)
        {
            if (id != emailcs.emailId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emailcs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmailcsExists(emailcs.emailId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(emailcs);
        }

        [Authorize]
        // GET: Emailcs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var emailcs = await _context.emails
                .FirstOrDefaultAsync(m => m.emailId == id);
            if (emailcs == null)
            {
                return NotFound();
            }

            return View(emailcs);
        }

        [Authorize]
        // POST: Emailcs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var emailcs = await _context.emails.FindAsync(id);
            _context.emails.Remove(emailcs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmailcsExists(int id)
        {
            return _context.emails.Any(e => e.emailId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SugartwebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @if (SignInManager.IsSignedIn(User))
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">🖼</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre nosotros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="" asp-controller="Home" asp-action="IndexAdmin">Panel de control</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    }
    else
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">🖼</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre nosotros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Arts" asp-action="IndexPublic2">Todas las obras</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Arts" asp-action="BuscarObra">Buscador de obras de arte🔍</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Emailcs" asp-action="Create">Contacto 📮</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    }

    <footer class="border-top footer text-light bg-danger">
        <div class="container">
            &copy; 2021 - by : Cristian Guajardo - <a asp-area="" asp-controller="Home" asp-action="Index" class="text-info">Inicio</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>